version: '3.8'

services:
  sultan-node:
    image: ghcr.io/cosmos/simapp:v0.50.0
    container_name: sultan-cosmos-real
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "1317:1317"    # REST API
      - "9090:9090"    # gRPC
    environment:
      - CHAIN_ID=sultan-1
    volumes:
      - ./sultan-data:/root/.simapp
    command: |
      sh -c "
        if [ ! -f /root/.simapp/config/genesis.json ]; then
          simd init sultan-node --chain-id sultan-1
          simd keys add validator --keyring-backend test
          simd genesis add-genesis-account validator 1000000000stake --keyring-backend test
          simd genesis gentx validator 100000000stake --keyring-backend test --chain-id sultan-1
          simd genesis collect-gentxs
        fi
        simd start --minimum-gas-prices 0stake
      "
