#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         SULTAN CHAIN TESTNET - OFFICIAL LAUNCH                ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "🎉 TESTNET IS LIVE!"
echo ""
echo "📍 API Endpoint: https://orange-telegram-pj6qgwgv59jjfrj9j-3030.app.github.dev/"
echo ""
echo "✨ Features Available NOW:"
echo "  • Zero gas fees on ALL transactions"
echo "  • 13.33% APY staking rewards"
echo "  • 18.66% APY for mobile validators"
echo "  • Wallet creation and management"
echo "  • Token transfers"
echo ""
echo "📱 Share this announcement:"
echo ""
echo "🐦 Twitter/X:"
echo "🚀 Sultan Chain Testnet is LIVE!"
echo "✅ Zero gas fees FOREVER"
echo "✅ 13.33% APY staking"  
echo "✅ Mobile validators earn 18.66%"
echo "Try it now: https://orange-telegram-pj6qgwgv59jjfrj9j-3030.app.github.dev/"
echo "#SultanChain #ZeroFees #DeFi #Web3"
