apiVersion: apps/v1
kind: Deployment
metadata:
  name: sultan-mainnet
  namespace: sultan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sultan-node
  template:
    metadata:
      labels:
        app: sultan-node
    spec:
      containers:
      - name: sultan
        image: sultan-chain:mainnet
        ports:
        - containerPort: 26657
          name: rpc
        - containerPort: 26656
          name: p2p
        env:
        - name: CHAIN_ID
          value: "sultan-mainnet-1"
        - name: ZERO_GAS
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: sultan-rpc
  namespace: sultan
spec:
  selector:
    app: sultan-node
  ports:
  - port: 26657
    targetPort: 26657
    name: rpc
  - port: 26656
    targetPort: 26656
    name: p2p
  type: LoadBalancer
