#!/usr/bin/env bash
export SULTAN_DB_ADDR="${SULTAN_DB_ADDR:-127.0.0.1:9042}"
export SULTAN_METRICS_PORT="${SULTAN_METRICS_PORT:-9105}"
export SULTAN_JWT_ALLOW_RAW=0
: "${SULTAN_JWT_SECRET:=change-this-secret}"
export SULTAN_JWT_SECRET
# Optional: echo "Env set. DB=$SULTAN_DB_ADDR METRICS=$SULTAN_METRICS_PORT RAW=$SULTAN_JWT_ALLOW_RAW"
