#!/bin/bash
set -e

# Sultan Blockchain - Production Deployment to Hetzner
# This script deploys the Sultan node with RPC endpoints to your Hetzner VPS

echo "🚀 Sultan Blockchain - Production Deployment"
echo "============================================="

# Configuration
SERVER_IP="${SERVER_IP:-your-hetzner-ip}"
SERVER_USER="${SERVER_USER:-root}"
DOMAIN="${DOMAIN:-sultanchain.io}"
RPC_DOMAIN="rpc.${DOMAIN}"

echo ""
echo "📋 Deployment Configuration:"
echo "  Server: $SERVER_USER@$SERVER_IP"
echo "  Domain: $DOMAIN"
echo "  RPC Endpoint: https://$RPC_DOMAIN"
echo ""

# Step 1: Build release binary locally
echo "🔨 Step 1: Building release binary..."
cargo build -p sultan-core --bin sultan-node --release

if [ ! -f "target/release/sultan-node" ]; then
    echo "❌ Build failed - binary not found"
    exit 1
fi

echo "✅ Binary built: $(ls -lh target/release/sultan-node | awk '{print $5}')"

# Step 2: Create deployment package
echo ""
echo "📦 Step 2: Creating deployment package..."
mkdir -p deploy-package
cp target/release/sultan-node deploy-package/
cp -r SULTAN deploy-package/ 2>/dev/null || true

# Create systemd service file
cat > deploy-package/sultan-node.service <<EOF
[Unit]
Description=Sultan Blockchain Node
After=network.target

[Service]
Type=simple
User=sultan
WorkingDirectory=/opt/sultan
ExecStart=/opt/sultan/sultan-node --validator --validator-address genesis --validator-stake 10000000 --rpc-addr 0.0.0.0:26657 --data-dir /var/lib/sultan
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=sultan-node

# Security
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/sultan

[Install]
WantedBy=multi-user.target
EOF

# Create nginx configuration
cat > deploy-package/nginx-sultan.conf <<EOF
# Sultan RPC Endpoint
upstream sultan_rpc {
    server 127.0.0.1:26657;
    keepalive 32;
}

server {
    listen 80;
    server_name $RPC_DOMAIN;
    
    # Redirect to HTTPS
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name $RPC_DOMAIN;
    
    # SSL certificates (will be generated by certbot)
    ssl_certificate /etc/letsencrypt/live/$RPC_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$RPC_DOMAIN/privkey.pem;
    
    # SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    
    # CORS headers for RPC
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
    
    # Preflight requests
    if (\$request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
    }
    
    location / {
        proxy_pass http://sultan_rpc;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # Timeouts for blockchain RPC
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    # Health check endpoint
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
EOF

# Create installation script for server
cat > deploy-package/install.sh <<'INSTALL_EOF'
#!/bin/bash
set -e

echo "🔧 Installing Sultan Node on server..."

# Create user and directories
if ! id -u sultan >/dev/null 2>&1; then
    useradd -r -s /bin/false -d /opt/sultan sultan
    echo "✅ Created sultan user"
fi

mkdir -p /opt/sultan
mkdir -p /var/lib/sultan
chown -R sultan:sultan /opt/sultan /var/lib/sultan

# Install binary
cp sultan-node /opt/sultan/
chmod +x /opt/sultan/sultan-node
chown sultan:sultan /opt/sultan/sultan-node
echo "✅ Installed sultan-node binary"

# Install systemd service
cp sultan-node.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable sultan-node
echo "✅ Installed systemd service"

# Install nginx if not present
if ! command -v nginx &> /dev/null; then
    apt-get update
    apt-get install -y nginx certbot python3-certbot-nginx
    echo "✅ Installed nginx"
fi

# Install nginx config
cp nginx-sultan.conf /etc/nginx/sites-available/sultan
ln -sf /etc/nginx/sites-available/sultan /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx
echo "✅ Configured nginx"

echo ""
echo "🎉 Installation complete!"
echo ""
echo "Next steps:"
echo "  1. Set up SSL: certbot --nginx -d rpc.sultanchain.io"
echo "  2. Start node: systemctl start sultan-node"
echo "  3. Check logs: journalctl -fu sultan-node"
echo "  4. Test RPC: curl http://localhost:26657/status"
INSTALL_EOF

chmod +x deploy-package/install.sh

echo "✅ Deployment package created"

# Step 3: Upload to server
echo ""
echo "📤 Step 3: Uploading to server..."
read -p "Enter server IP or hostname: " SERVER_IP

if [ -z "$SERVER_IP" ]; then
    echo "❌ No server IP provided"
    exit 1
fi

echo "Uploading to $SERVER_USER@$SERVER_IP..."
scp -r deploy-package/* $SERVER_USER@$SERVER_IP:/tmp/sultan-deploy/

echo "✅ Files uploaded"

# Step 4: Run installation on server
echo ""
echo "🔧 Step 4: Running installation on server..."
ssh $SERVER_USER@$SERVER_IP <<'REMOTE_EOF'
cd /tmp/sultan-deploy
bash install.sh
REMOTE_EOF

echo "✅ Installation complete"

# Step 5: Configure SSL
echo ""
echo "🔐 Step 5: Setting up SSL..."
read -p "Configure SSL now? (y/n): " SETUP_SSL

if [ "$SETUP_SSL" = "y" ]; then
    read -p "Enter your email for Let's Encrypt: " EMAIL
    read -p "Enter RPC domain (e.g., rpc.sultanchain.io): " RPC_DOMAIN
    
    ssh $SERVER_USER@$SERVER_IP "certbot --nginx -d $RPC_DOMAIN --non-interactive --agree-tos -m $EMAIL"
    echo "✅ SSL configured"
fi

# Step 6: Start the node
echo ""
echo "🚀 Step 6: Starting Sultan node..."
ssh $SERVER_USER@$SERVER_IP "systemctl start sultan-node"
sleep 5

echo ""
echo "📊 Checking node status..."
ssh $SERVER_USER@$SERVER_IP "systemctl status sultan-node --no-pager"

echo ""
echo "🧪 Testing RPC endpoint..."
ssh $SERVER_USER@$SERVER_IP "curl -s http://localhost:26657/status | head -5"

echo ""
echo "✅ Deployment complete!"
echo ""
echo "📍 Your Sultan RPC endpoint: https://$RPC_DOMAIN"
echo ""
echo "🔗 Test endpoints:"
echo "  curl https://$RPC_DOMAIN/status"
echo "  curl https://$RPC_DOMAIN/tokens/list"
echo "  curl https://$RPC_DOMAIN/dex/pools"
echo ""
echo "📝 Useful commands on server:"
echo "  systemctl status sultan-node    # Check status"
echo "  journalctl -fu sultan-node      # Watch logs"
echo "  systemctl restart sultan-node   # Restart node"
echo ""
